name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to 'master' if your default branch is master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.38.9'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        # The base-href flag ensures assets load correctly from your subfolder URL
        run: flutter build web --base-href "/portfolio_site/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages # The target branch where build files will live